### ISSUE TITLE
You may add a bit text stating that this project is no more active

### ISSUE THREAD

**Issue by javierjeronimo** [thesp0nge/owasp-orizon#3]

**Comment by thesp0nge** [comment]
Maybe you can contribuite instead of trolling

Il 10 mag 2017 15:58, "Javier Jerónimo" <notifications@github.com> ha
scritto:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thesp0nge/owasp-orizon/issues/3>, or mute the thread

**Comment by javierjeronimo** [comment]
Sorry if I sounded like a troll, it wasn't my intention. I was really interested in this project and tried to run it locally, but found that the execution did nothing. Maybe I checked out the wrong branch or missed something in the setup.

Anyway, the problem is that it was linked from a rencently updated page in OWASP Wiki, but in fact, looking at the project page in OWASP, it is listed as an inactive one.

Thats the reason I asked you to put a note stating it is inactive, just in case it is visited from a search result or linked from anywhere different that its project page in OWASP.

Regards.

**Comment by thesp0nge** [comment]
On the upcoming Owasp Summit, there will be a session to help people rebooting the project (http://owaspsummit.org/Working-Sessions/Project-Summit/Owasp-Orizon-Reboot.html).

Owasp Orizon was marked as Inactive because I didn't update a Wiki but this is, IMHO, a very bottom priority.

The most, and difficult in the cybersecurity world, concern is to build an ecosystem of people working on it. The same, it was very easy to me with dawnscanner project since ruby guys love writing code. Unfortunately, very few cybersec guys love writing stuff.

So the project is trying to reboot, very slowly, but it's far from being inactive

**Comment by gitnachogo** [comment]
What is the state of the project actually? I'm a developer studying a cybersecurity master, and I'd like to contribute to some open-source projects related to cybersecurity, but of course, I'd like if it has a community behind and I'm not the only one hehehehe
